# Generated by Django 4.2.8 on 2024-01-14 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 12, 52, 8, 857962, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
