# Generated by Django 4.2.8 on 2023-12-20 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0003_alter_insurance_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 7, 59, 13, 199300, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 19, 7, 59, 13, 199276, tzinfo=datetime.timezone.utc), verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 7, 59, 13, 199261, tzinfo=datetime.timezone.utc), verbose_name='Дата начала'),
        ),
    ]
