# Generated by Django 4.2.8 on 2023-12-26 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0006_insurance_moderator_alter_insurance_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='bankrupt',
            field=models.IntegerField(default=-1, verbose_name='Банкрот'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 16, 35, 27, 68005, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 25, 16, 35, 27, 67977, tzinfo=datetime.timezone.utc), verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 16, 35, 27, 67961, tzinfo=datetime.timezone.utc), verbose_name='Дата начала'),
        ),
    ]
