# Generated by Django 4.2.8 on 2023-12-26 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0008_alter_insurance_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='bankrupt',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 17, 12, 50, 985302, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 25, 17, 12, 50, 985276, tzinfo=datetime.timezone.utc), verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 17, 12, 50, 985261, tzinfo=datetime.timezone.utc), verbose_name='Дата начала'),
        ),
    ]
