# Generated by Django 4.2.8 on 2024-01-10 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0009_remove_insurance_bankrupt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 15, 53, 40, 612081, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 9, 15, 53, 40, 612056, tzinfo=datetime.timezone.utc), verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 10, 15, 53, 40, 612042, tzinfo=datetime.timezone.utc), verbose_name='Дата начала'),
        ),
    ]
