# Generated by Django 4.2.8 on 2024-01-10 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0010_rename_user_insurance_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='date_of_formation',
            new_name='date_formation',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='insurance_type',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='vehicle_license_plate',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='vehicle_vin',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='vehicle_year',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 18, 12, 10, 920662, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
