# Generated by Django 4.2.8 on 2024-01-10 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0011_rename_date_of_formation_insurance_date_formation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurance',
            options={'ordering': ('-date_formation',), 'verbose_name': 'Страховка', 'verbose_name_plural': 'Страховки'},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driver_license_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='issue_date',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 18, 33, 48, 34602, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
