# Generated by Django 4.2.5 on 2023-11-20 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Иванов Иван Иванович', max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField()),
                ('address', models.CharField(default='Москва', max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(default='+7-999-999-99-99', max_length=17, verbose_name='Телефон')),
                ('email', models.CharField(default='asd@gmail.com', max_length=255, verbose_name='Емейл')),
                ('driver_license_number', models.CharField(default='9999 999999', max_length=20, verbose_name='ВУ')),
                ('issue_date', models.DateField(default='2020-05-05', verbose_name='Дата получения')),
                ('expiration_date', models.DateField(default='2050-05-05', verbose_name='Срок действия до')),
                ('passport_number', models.CharField(default='9999 999999', max_length=11, verbose_name='Паспорт')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(default='drivers/img1.png', upload_to='drivers', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата конца')),
                ('premium_amount', models.FloatField(default=9999.99, verbose_name='Сумма')),
                ('insurance_type', models.BooleanField()),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершён'), (4, 'Отменён'), (5, 'Удалён')], default=1, verbose_name='Статус')),
                ('date_create', models.DateTimeField(default=datetime.datetime(2023, 11, 20, 17, 30, 7, 42724, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_form', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('date_over', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('vehicle_make', models.CharField(max_length=50, verbose_name='Марка')),
                ('vehicle_model', models.CharField(max_length=50, verbose_name='Модель')),
                ('vehicle_year', models.CharField(max_length=4, verbose_name='Год выпуска')),
                ('vehicle_vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('vehicle_license_plate', models.CharField(max_length=10, verbose_name='Гос. номер')),
                ('drivers', models.ManyToManyField(null=True, to='bmstu_lab.driver', verbose_name='Водители')),
            ],
            options={
                'verbose_name': 'Страховка',
                'verbose_name_plural': 'Страховки',
            },
        ),
    ]
