# Generated by Django 4.2.5 on 2023-10-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_license_number', models.CharField(max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.BooleanField()),
                ('url_photo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverInsurance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'driver_insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('premium_amount', models.FloatField()),
                ('insurance_type', models.BooleanField()),
                ('status', models.CharField(max_length=20)),
                ('date_create', models.DateField(blank=True, null=True)),
                ('date_form', models.DateField(blank=True, null=True)),
                ('date_over', models.DateField(blank=True, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_year', models.CharField(blank=True, max_length=4, null=True)),
                ('vehicle_vin', models.CharField(blank=True, max_length=17, null=True)),
                ('vehicle_license_plate', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('admin', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
