# Generated by Django 4.2.5 on 2023-11-20 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 17, 40, 3, 322966, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
