# Generated by Django 4.2.5 on 2023-11-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0003_alter_driver_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='driverinsurance',
            table='driverinsurance',
        ),
    ]
