# Generated by Django 4.2.5 on 2023-11-27 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0003_alter_insurance_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='user', max_length=255, verbose_name='Логин')),
                ('password', models.CharField(default='user', max_length=255, verbose_name='Пароль')),
                ('admin', models.BooleanField(default=False, verbose_name='Статус модератора')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterField(
            model_name='insurance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 17, 37, 59, 127233, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 26, 20, 37, 59, 127198), verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 20, 37, 59, 127185), verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.users', verbose_name='Пользователь'),
        ),
    ]
