# Generated by Django 4.2.5 on 2023-11-20 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0004_alter_insurance_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 19, 0, 29, 19824, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
