# Generated by Django 4.2.5 on 2023-11-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0004_alter_driverinsurance_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverinsurance',
            options={},
        ),
    ]
