# Generated by Django 4.2.5 on 2023-11-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0005_alter_driverinsurance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverinsurance',
            options={'managed': False},
        ),
    ]
