# Generated by Django 4.2.8 on 2023-12-20 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0006_alter_insurance_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='bmstu_lab.users', verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 17, 6, 9, 459616, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 19, 20, 6, 9, 459580), verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 20, 6, 9, 459567), verbose_name='Дата начала'),
        ),
    ]
