# Generated by Django 4.2.8 on 2023-12-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0006_alter_driverinsurance_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='driverinsurance',
            table='driver_insurance',
        ),
    ]
